apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer
  namespace: fintlabs-no
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-core-consumer-exceptions:latest
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.fint-core.event.consumer-error'
        permission: read
  resources:
    limits:
      memory: "1024Mi"
      cpu: "250m"
    requests:
      memory: "128Mi"
      cpu: "100m"